### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by ThaddeusKKR** [ThaddeusKKR/Ichigo#1]
**This is Ichigo's current to-do list.**

- [ ] Finish `discord-player` events
- [ ] Per-server prefix customisation
- [ ] Finish music commands
- [ ] Add an `eval` command
- [ ] More coming soon, these are priorities.

*To report a bug or suggest something, please either make a new issue or comment on this one.*
